const products = [
  {
    id: 1,
    name: "Apple",
    category: "Fruit",
    description: "A round fruit with a red, green, or yellow ",
    price: 89,
    rating: 5,
    discount: 0,
    images: [
      "./assets/images/products/0.png",
      "./assets/images/products/1.png",
      "./assets/images/products/2.png",
      "./assets/images/products/3.png",
      "./assets/images/products/4.png",
    ],
  },
  {
    id: 2,
    name: "Banana",
    category: "Fruit",
    description:
      "A long, curved fruit with a yellow skin and sweet, creamy white flesh.",
    price: 71,
    rating: 5,
    discount: 20,
    images: [
      "./assets/images/products/5.png",
      "./assets/images/products/6.png",
      "./assets/images/products/7.png",
      "./assets/images/products/8.png",
      "./assets/images/products/9.png",
    ],
  },
  {
    id: 3,
    name: "Bread",
    category: "Bakery",
    description:
      "A staple food made from flour, water, and yeast, baked into a loaf.",
    price: 88,
    rating: 5,
    discount: 20,
    images: [
      "./assets/images/products/10.png",
      "./assets/images/products/11.png",
      "./assets/images/products/12.png",
      "./assets/images/products/13.png",
      "./assets/images/products/14.png",
    ],
  },
  {
    id: 4,
    name: "Broccoli",
    category: "Vegetable",
    description:
      "A green vegetable with a tree-like appearance, known for its high nutrient content.",
    price: 94,
    rating: 4.5,
    discount: 20,
    images: [
      "./assets/images/products/15.png",
      "./assets/images/products/16.png",
      "./assets/images/products/17.png",
      "./assets/images/products/18.png",
      "./assets/images/products/19.png",
    ],
  },
  {
    id: 5,
    name: "Carrot",
    category: "Vegetable",
    description:
      "A root vegetable with a crunchy texture and a sweet, earthy flavor.",
    price: 82,
    rating: 5,
    discount: 20,
    images: [
      "./assets/images/products/20.png",
      "./assets/images/products/21.png",
      "./assets/images/products/22.png",
      "./assets/images/products/23.png",
      "./assets/images/products/24.png",
    ],
  },
  {
    id: 6,
    name: "Cheese",
    category: "Dairy",
    description:
      "A dairy product made from milk, with a variety of textures and flavors.",
    price: 91,
    rating: 3.5,
    discount: 50,
    images: [
      "./assets/images/products/25.png",
      "./assets/images/products/26.png",
      "./assets/images/products/27.png",
      "./assets/images/products/28.png",
      "./assets/images/products/29.png",
    ],
  },
  {
    id: 7,
    name: "Chicken",
    category: "Meat",
    description:
      "A type of poultry, often used as a source of protein in meals.",
    price: 68,
    rating: 3.5,
    discount: 20,
    images: [
      "./assets/images/products/30.png",
      "./assets/images/products/31.png",
      "./assets/images/products/32.png",
      "./assets/images/products/33.png",
      "./assets/images/products/34.png",
    ],
  },
  {
    id: 8,
    name: "Chocolate",
    category: "Dessert",
    description:
      "A sweet food made from cacao beans, used in a variety of desserts and confections.",
    price: 61,
    rating: 4.5,
    discount: 20,
    images: [
      "./assets/images/products/35.png",
      "./assets/images/products/36.png",
      "./assets/images/products/37.png",
      "./assets/images/products/38.png",
      "./assets/images/products/39.png",
    ],
  },
  {
    id: 9,
    name: "Coffee",
    category: "Dessert",
    description:
      "A dark, bitter beverage made from roasted coffee beans, typically used as a pick-me-up.",
    price: 98,
    rating: 5,
    discount: 20,
    images: [
      "./assets/images/products/40.png",
      "./assets/images/products/41.png",
      "./assets/images/products/42.png",
      "./assets/images/products/43.png",
      "./assets/images/products/44.png",
    ],
  },
  {
    id: 10,
    name: "Egg",
    category: "Dairy",
    description:
      "A oval-shaped reproductive body produced by birds, often used as a source of protein in meals.",
    price: 79,
    rating: 4.5,
    discount: 0,
    images: [
      "./assets/images/products/45.png",
      "./assets/images/products/46.png",
      "./assets/images/products/47.png",
      "./assets/images/products/48.png",
      "./assets/images/products/49.png",
    ],
  },
  {
    id: 11,
    name: "Fish",
    category: "Meat",
    description:
      "A type of seafood, known for its omega-3 fatty acids and high protein content.",
    price: 89,
    rating: 3.5,
    discount: 50,
    images: [
      "./assets/images/products/50.png",
      "./assets/images/products/51.png",
      "./assets/images/products/52.png",
      "./assets/images/products/53.png",
      "./assets/images/products/54.png",
    ],
  },
  {
    id: 12,
    name: "Grapes",
    category: "Fruit",
    description:
      "A small, sweet fruit that grows in clusters, often used in wine-making.",
    price: 61,
    rating: 4,
    discount: 20,
    images: [
      "./assets/images/products/55.png",
      "./assets/images/products/56.png",
      "./assets/images/products/57.png",
      "./assets/images/products/58.png",
      "./assets/images/products/59.png",
    ],
  },
  {
    id: 13,
    name: "Hamburger",
    category: "Fast food",
    description:
      "A sandwich made with a patty of ground beef, served on a bun with various toppings.",
    price: 87,
    rating: 5,
    discount: 0,
    images: [
      "./assets/images/products/60.png",
      "./assets/images/products/61.png",
      "./assets/images/products/62.png",
      "./assets/images/products/63.png",
      "./assets/images/products/64.png",
    ],
  },
  {
    id: 14,
    name: "Hot dog",
    category: "Fast food",
    description:
      "A type of sausage served in a long roll, often used as a quick and convenient food.",
    price: 84,
    rating: 4.5,
    discount: 50,
    images: [
      "./assets/images/products/65.png",
      "./assets/images/products/66.png",
      "./assets/images/products/67.png",
      "./assets/images/products/68.png",
      "./assets/images/products/69.png",
    ],
  },
  {
    id: 15,
    name: "Ice cream",
    category: "Dessert",
    description:
      "A frozen dessert made from cream, sugar, and flavorings, available in a variety of flavors.",
    price: 68,
    rating: 4.5,
    discount: 0,
    images: [
      "./assets/images/products/70.png",
      "./assets/images/products/71.png",
      "./assets/images/products/72.png",
      "./assets/images/products/73.png",
      "./assets/images/products/74.png",
    ],
  },
  {
    id: 16,
    name: "Lemon",
    category: "Fruit",
    description:
      "A yellow citrus fruit with a tart, acidic flavor, often used in cooking and baking.",
    price: 74,
    rating: 3.5,
    discount: 0,
    images: [
      "./assets/images/products/75.png",
      "./assets/images/products/76.png",
      "./assets/images/products/77.png",
      "./assets/images/products/78.png",
      "./assets/images/products/79.png",
    ],
  },
  {
    id: 17,
    name: "Eggs",
    category: "Dairy",
    description:
      "Eggs are oval-shaped reproductive structures produced by female birds and some reptiles.",
    price: 70,
    rating: 4.5,
    discount: 50,
    images: [
      "./assets/images/products/45.png",
      "./assets/images/products/46.png",
      "./assets/images/products/47.png",
      "./assets/images/products/48.png",
      "./assets/images/products/49.png",
    ],
  },
  {
    id: 18,
    name: "Honey",
    category: "Dairy",
    description:
      "Honey is a sweet, sticky liquid made by bees from the nectar of flowers.",
    price: 87,
    rating: 4,
    discount: 0,
    images: [
      "./assets/images/products/85.png",
      "./assets/images/products/86.png",
      "./assets/images/products/87.png",
      "./assets/images/products/88.png",
      "./assets/images/products/89.png",
    ],
  },
  {
    id: 19,
    name: "Ice Cream",
    category: "Dessert",
    description:
      "Ice cream is a frozen dessert made from cream, sugar, and flavorings.",
    price: 83,
    rating: 4.5,
    discount: 0,
    images: [
      "./assets/images/products/70.png",
      "./assets/images/products/71.png",
      "./assets/images/products/72.png",
      "./assets/images/products/73.png",
      "./assets/images/products/74.png",
    ],
  },
  {
    id: 20,
    name: "Jelly",
    category: "Fruit",
    description:
      "Jelly is a sweet spread made from fruit juice and sugar, often used as a topping for toast or pastries.",
    price: 76,
    rating: 5,
    discount: 0,
    images: [
      "./assets/images/products/95.png",
      "./assets/images/products/96.png",
      "./assets/images/products/97.png",
      "./assets/images/products/98.png",
      "./assets/images/products/99.png",
    ],
  },
  {
    id: 21,
    name: "Ketchup",
    category: "Dairy",
    description:
      "Ketchup is a tangy sauce made from tomatoes, vinegar, sugar, and spices.",
    price: 77,
    rating: 5,
    discount: 0,
    images: [
      "./assets/images/products/100.png",
      "./assets/images/products/101.png",
      "./assets/images/products/102.png",
      "./assets/images/products/103.png",
      "./assets/images/products/104.png",
    ],
  },
  {
    id: 22,
    name: "Mango",
    category: "Fruit",
    description:
      "Mangoes are juicy, sweet tropical fruits with a fleshy interior and a large, oblong seed in the center.",
    price: 80,
    rating: 5,
    discount: 20,
    images: [
      "./assets/images/products/105.png",
      "./assets/images/products/106.png",
      "./assets/images/products/107.png",
      "./assets/images/products/108.png",
      "./assets/images/products/109.png",
    ],
  },
  {
    id: 23,
    name: "Noodles",
    category: "Meat",
    description:
      "Noodles are a type of pasta made from wheat flour and water, often used in Asian cuisine.",
    price: 93,
    rating: 3.5,
    discount: 20,
    images: [
      "./assets/images/products/110.png",
      "./assets/images/products/111.png",
      "./assets/images/products/112.png",
      "./assets/images/products/113.png",
      "./assets/images/products/114.png",
    ],
  },
  {
    id: 24,
    name: "Oatmeal",
    category: "Breakfast",
    description:
      "Oatmeal is a type of porridge made from oats that is often served for breakfast.",
    price: 94,
    rating: 4.5,
    discount: 0,
    images: [
      "./assets/images/products/115.png",
      "./assets/images/products/116.png",
      "./assets/images/products/117.png",
      "./assets/images/products/118.png",
      "./assets/images/products/119.png",
    ],
  },
  {
    id: 25,
    name: "Bacon",
    category: "Breakfast",
    description:
      "Bacon is a popular breakfast food made from cured pork belly, it is newly delivered.",
    price: 71,
    rating: 3.5,
    discount: 20,
    images: [
      "./assets/images/products/120.png",
      "./assets/images/products/121.png",
      "./assets/images/products/122.png",
      "./assets/images/products/123.png",
      "./assets/images/products/124.png",
    ],
  },
  {
    id: 26,
    name: "Pancakes",
    category: "Breakfast",
    description:
      "Pancakes are a popular breakfast food made from flour, eggs, and milk.",
    price: 63,
    rating: 4,
    discount: 0,
    images: [
      "./assets/images/products/125.png",
      "./assets/images/products/126.png",
      "./assets/images/products/127.png",
      "./assets/images/products/128.png",
      "./assets/images/products/129.png",
    ],
  },
  {
    id: 27,
    name: "Waffles",
    category: "Breakfast",
    description:
      "Waffles are a type of breakfast food made from batter cooked in a waffle iron.",
    price: 97,
    rating: 4.5,
    discount: 20,
    images: [
      "./assets/images/products/130.png",
      "./assets/images/products/131.png",
      "./assets/images/products/132.png",
      "./assets/images/products/133.png",
      "./assets/images/products/134.png",
    ],
  },
  {
    id: 28,
    name: "Fried Rice",
    category: "Lunch",
    description:
      "Fried Rice is a type of rice dish that is stir-fried in a pan with oil and other ingredients.",
    price: 81,
    rating: 4,
    discount: 20,
    images: [
      "./assets/images/products/135.png",
      "./assets/images/products/136.png",
      "./assets/images/products/137.png",
      "./assets/images/products/138.png",
      "./assets/images/products/139.png",
    ],
  },
  {
    id: 29,
    name: "Spaghetti",
    category: "Lunch",
    description:
      "Spaghetti is a type of pasta made from wheat flour and water, usually served with sauce.",
    price: 96,
    rating: 3,
    discount: 50,
    images: [
      "./assets/images/products/140.png",
      "./assets/images/products/141.png",
      "./assets/images/products/142.png",
      "./assets/images/products/143.png",
      "./assets/images/products/144.png",
    ],
  },
  {
    id: 30,
    name: "Pizza",
    category: "Lunch",
    description:
      "Pizza is a popular dish made from dough, sauce, cheese, and toppings.",
    price: 95,
    rating: 4,
    discount: 0,
    images: [
      "./assets/images/products/145.png",
      "./assets/images/products/146.png",
      "./assets/images/products/147.png",
      "./assets/images/products/148.png",
      "./assets/images/products/149.png",
    ],
  },
  {
    id: 31,
    name: "Grilled Cheese",
    category: "Lunch",
    description:
      "A grilled cheese sandwich is a hot sandwich made from cheese and bread.",
    price: 100,
    rating: 5,
    discount: 50,
    images: [
      "./assets/images/products/150.png",
      "./assets/images/products/151.png",
      "./assets/images/products/152.png",
      "./assets/images/products/153.png",
      "./assets/images/products/154.png",
    ],
  },
  {
    id: 32,
    name: "Steak",
    category: "Dinner",
    description:
      "Steak is a popular dinner dish made from a cut of beef that is usually grilled or pan-fried.",
    price: 63,
    rating: 4.5,
    discount: 20,
    images: [
      "./assets/images/products/155.png",
      "./assets/images/products/156.png",
      "./assets/images/products/157.png",
      "./assets/images/products/158.png",
      "./assets/images/products/159.png",
    ],
  },
  {
    id: 33,
    name: "Salmon",
    category: "Dinner",
    description:
      "Salmon is a type of fish that is often grilled or baked and served as a main course.",
    price: 82,
    rating: 4.5,
    discount: 20,
    images: [
      "./assets/images/products/160.png",
      "./assets/images/products/161.png",
      "./assets/images/products/162.png",
      "./assets/images/products/163.png",
      "./assets/images/products/164.png",
    ],
  },
  {
    id: 34,
    name: "Chicken Alfredo",
    category: "Dinner",
    description:
      "Chicken Alfredo is a pasta dish made with chicken, alsjfkdlkasdfhlkjh.",
    price: 94,
    rating: 4,
    discount: 20,
    images: [
      "./assets/images/products/165.png",
      "./assets/images/products/166.png",
      "./assets/images/products/167.png",
      "./assets/images/products/168.png",
      "./assets/images/products/169.png",
    ],
  },
  {
    id: 35,
    name: "Lasagna",
    category: "Dinner",
    description:
      "Lasagna is a type of pasta dish made with layers of pasta, sauce, cheese, and meat or vegetables.",
    price: 70,
    rating: 1,
    discount: 0,
    images: [
      "./assets/images/products/170.png",
      "./assets/images/products/171.png",
      "./assets/images/products/172.png",
      "./assets/images/products/173.png",
      "./assets/images/products/174.png",
    ],
  },
  {
    id: 36,
    name: "Chocolate Chip",
    category: "Dessert",
    description:
      "Chocolate Chip Cookies are a type of cookie made from flour, sugar, butter, and chocolate chips.",
    price: 98,
    rating: 3.5,
    discount: 0,
    images: [
      "./assets/images/products/175.png",
      "./assets/images/products/176.png",
      "./assets/images/products/177.png",
      "./assets/images/products/178.png",
      "./assets/images/products/179.png",
    ],
  },
];
